ALTER TABLE CITIES_TO_WATCH ADD COLUMN city_name TEXT;
ALTER TABLE CITIES_TO_WATCH ADD COLUMN country_code TEXT;
ALTER TABLE CITIES_TO_WATCH ADD COLUMN longitude REAL NOT NULL DEFAULT 0;
ALTER TABLE CITIES_TO_WATCH ADD COLUMN latitude REAL NOT NULL DEFAULT 0;
